openapi: "3.0.0"
info:
    version: 1.1.0
    title: Reddit.com
    description: Reddit.com API
    termsOfService: https://www.reddit.com/wiki/api-terms
    contact:
        name: Reddit API Access
        url: https://ssl.reddit.com/dev/api
        email: api@reddit.com
    license:
        name: MIT
        url: https://opensource.org/licenses/MIT
servers:
    -
        url: https://oauth.reddit.com
        description: Reddit.com API
components:
    securitySchemes:
        oauth2:
            type: oauth2
            flows:
                authorizationCode:
                    authorizationUrl: /authorize
                    tokenUrl: /access_token
                    scopes: {}
paths:
    /me:
        $ref: ./paths/me.yaml
    /user/{username}/saved:
        $ref: ./paths/saved.yaml
